name: SmartClass CI/CD

on:
  push:
    branches: ["main"]

jobs:
  attendance-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout SmartClass code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pytest
        run: pip install pytest

      - name: Test Attendance Feature
        run: pytest test_attendance.py

      - name: Run Attendance Feature
        run: python attendance.py
